import api from '@/api/axios';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useQuery } from '@tanstack/react-query'
import { format } from 'date-fns';
import React from 'react'

const fetchReports = async ({ queryKey }) => {
    const [_key] = queryKey;
    const res = await api.get('/reports');

    return res.data;
}

const ReportsAndSolutions = () => {
    const { data, isLoading, isFetching } = useQuery({
        queryKey: ['reports'],
        queryFn: fetchReports,
        enabled: true,
        staleTime: 5 * 60 * 1000,
    });

    const reports = data ?? [];

    return (
        <div className="space-y-6">
            <div className="flex gap-6 flex-col lg:flex-row lg:items-center lg:justify-between">
                <div>
                    <h2 className="text-2xl font-bold">Reports and Solutions</h2>
                    <p className="text-muted-foreground">Reports and solutions generated by AI</p>
                </div>
            </div>
            
            <Card>
                <CardHeader>
                    <CardTitle>
                        List of Reports and Solutions
                    </CardTitle>
                </CardHeader>
                <CardContent className='flex flex-col gap-4'>
                    {isLoading ? (
                        <span>Loading...</span>
                    ) : reports?.length ? reports.map((item) => {
                        return (
                            <Card key={item.id} className='border border-primary'>
                                <CardHeader>
                                    <CardTitle>
                                        Generated on {format(new Date(item.created_at), 'PPp')}
                                    </CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <div dangerouslySetInnerHTML={{
                                    __html: item.body
                                        .replace(/\n/g, "<br>")
                                        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                                    }} />
                                </CardContent>
                                {/* <CardContent className='whitespace-pre-line'>
                                    {item.body}
                                </CardContent> */}
                            </Card>
                        )
                    }) : (
                        <span>No reports found.</span>
                    )}
                </CardContent>
            </Card>
        </div>
    )
}

export default ReportsAndSolutions
